<a href="https://www.kaggle.com/mihirpaghdal/amazon-ml-challenge?scriptVersionId=84552144" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import dask.dataframe as dd
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/amazon-ml-challenge-2021/train.csv


In [2]:
df = pd.read_csv('../input/amazon-ml-challenge-2021/train.csv',escapechar='\\',quoting = 3)

In [3]:
n = 10
top10 = df['BROWSE_NODE_ID'].value_counts()[:n].index.tolist()

In [4]:
top10

[1045, 5, 1251, 1052, 4, 1295, 1024, 374, 773, 1194]

In [5]:
df["BROWSE_NODE_ID"] = df["BROWSE_NODE_ID"].apply(lambda x : x if x in top10 else np.nan)
df.head()

TITLE  \
0         Pete The Cat Bedtime Blues Doll, 14.5 Inch   
1  The New Yorker NYHM014 Refrigerator Magnet, 2 ...   
2  The Ultimate Self-Sufficiency Handbook: A Comp...   
3   Amway Nutrilite Kids Chewable Iron Tablets (100)   
4  Teacher Planner Company A4 6 Lesson Academic T...   

                                         DESCRIPTION  \
0  Pete the Cat is the coolest, most popular cat ...   
1  The New Yorker Handsome Cello Wrapped Hard Mag...   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                                       BULLET_POINTS           BRAND  \
0  [Pete the Cat Bedtime Blues plush doll,Based o...     MerryMakers   
1  [Cat In A Tea Cup by New Yorker cover artist G...  The New Yorker   
2                                Skyhorse Publishing          imusti   
3  [Nutrilite Kids,Chewable Iron Tablets,Quantity...           Amway   
4                                                NaN             NaN   

   BROWSE_NODE_ID  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4             4.0

In [6]:
df.dropna(inplace = True)

In [7]:
df.reset_index()

index                                              TITLE  \
0             5  Men'S Full Sleeve Raglan T-Shirts Denim T-Shir...   
1            67               Prismacolor Verithin Colored Pencils   
2           213              Black Ops BMX Brush Off Grips 125mm B   
3           373  US Military T-shirt Soldier This We'll Defend-...   
4           374  Sony PCK-LM2AM - LCD Screen Protector - for a ...   
...         ...                                                ...   
434689  2902968  True Desire Camera Lens Protector,[High Defini...   
434690  2902977  MN Fashion's Summer Solid Cotton Kurti for Wom...   
434691  2902978  TIMBU Tempered Glass for Lephone W15 Full Scre...   
434692  2902984       Janasya Women's Red Rayon Kurta With Palazzo   
434693  2902995  Think Tech Desinger Printed Back Case Cover Co...   

                                              DESCRIPTION  \
0       Men'S Full Sleeve Raglan T-Shirts Denim T-Shir...   
1       High-performance, acid-free colored pencils de...   
2       72302 Color: Pastel Purple Features: Carrying ...   
3       Our patriotic clothing line comes in t-shirts,...   
4       Reduce the amount of scratches, fingerprints a...   
...                                                   ...   
434689  High Definition Film Screen High Definition cl...   
434690  this classy kurta is a beautiful manifestation...   
434691  ULTIMATE PROTECTION AND USABILITY: Our Premium...   
434692  Be the cynosure of all eyes by wearing kurta p...   
434693  This Think Tech Designer Printed Mobile Back C...   

                                            BULLET_POINTS              BRAND  \
0       [Color: Blue,Sleeve: Full Sleeve,Material: Cot...  Bhavya Enterprise   
1       [Points won't snap under normal pressure; mois...        PRISMACOLOR   
2       [Product Model No: 72302-Aeromat,Product Weigh...            Aeromat   
3       [Unisex Sizing fits both Men and Women, making...        Erazor Bits   
4       [Hard plastic cover,protect LCD screen from du...               Sony   
...                                                   ...                ...   
434689  [Specially Designed for Foco X2/Redmi K30 only...        True Desire   
434690  [Care Instructions: Gentle Machine / Hand Wash...            Generic   
434691  [HD Clarity with 100% transparency,Rounded edg...              TIMBU   
434692  [Material: Kurta-Rayon; Bottom-Pure Cotton,Sty...            Janasya   
434693  [It'S 3D Printing Technologies So Colour Will ...         Think Tech   

        BROWSE_NODE_ID  
0                  5.0  
1                  4.0  
2                  4.0  
3                  5.0  
4                374.0  
...                ...  
434689           374.0  
434690          1251.0  
434691           374.0  
434692          1251.0  
434693          1045.0  

[434694 rows x 6 columns]

In [8]:
df1 = df.copy()

In [9]:
df1.head()

TITLE  \
5    Men'S Full Sleeve Raglan T-Shirts Denim T-Shir...   
67                Prismacolor Verithin Colored Pencils   
213              Black Ops BMX Brush Off Grips 125mm B   
373  US Military T-shirt Soldier This We'll Defend-...   
374  Sony PCK-LM2AM - LCD Screen Protector - for a ...   

                                           DESCRIPTION  \
5    Men'S Full Sleeve Raglan T-Shirts Denim T-Shir...   
67   High-performance, acid-free colored pencils de...   
213  72302 Color: Pastel Purple Features: Carrying ...   
373  Our patriotic clothing line comes in t-shirts,...   
374  Reduce the amount of scratches, fingerprints a...   

                                         BULLET_POINTS              BRAND  \
5    [Color: Blue,Sleeve: Full Sleeve,Material: Cot...  Bhavya Enterprise   
67   [Points won't snap under normal pressure; mois...        PRISMACOLOR   
213  [Product Model No: 72302-Aeromat,Product Weigh...            Aeromat   
373  [Unisex Sizing fits both Men and Women, making...        Erazor Bits   
374  [Hard plastic cover,protect LCD screen from du...               Sony   

     BROWSE_NODE_ID  
5               5.0  
67              4.0  
213             4.0  
373             5.0  
374           374.0

In [10]:
df1["text"] = df1["TITLE"] + " " + df1["BRAND"]

In [11]:
df1.reset_index(inplace=True)

In [12]:
df1.head()

index                                              TITLE  \
0      5  Men'S Full Sleeve Raglan T-Shirts Denim T-Shir...   
1     67               Prismacolor Verithin Colored Pencils   
2    213              Black Ops BMX Brush Off Grips 125mm B   
3    373  US Military T-shirt Soldier This We'll Defend-...   
4    374  Sony PCK-LM2AM - LCD Screen Protector - for a ...   

                                         DESCRIPTION  \
0  Men'S Full Sleeve Raglan T-Shirts Denim T-Shir...   
1  High-performance, acid-free colored pencils de...   
2  72302 Color: Pastel Purple Features: Carrying ...   
3  Our patriotic clothing line comes in t-shirts,...   
4  Reduce the amount of scratches, fingerprints a...   

                                       BULLET_POINTS              BRAND  \
0  [Color: Blue,Sleeve: Full Sleeve,Material: Cot...  Bhavya Enterprise   
1  [Points won't snap under normal pressure; mois...        PRISMACOLOR   
2  [Product Model No: 72302-Aeromat,Product Weigh...            Aeromat   
3  [Unisex Sizing fits both Men and Women, making...        Erazor Bits   
4  [Hard plastic cover,protect LCD screen from du...               Sony   

   BROWSE_NODE_ID                                               text  
0             5.0  Men'S Full Sleeve Raglan T-Shirts Denim T-Shir...  
1             4.0   Prismacolor Verithin Colored Pencils PRISMACOLOR  
2             4.0      Black Ops BMX Brush Off Grips 125mm B Aeromat  
3             5.0  US Military T-shirt Soldier This We'll Defend-...  
4           374.0  Sony PCK-LM2AM - LCD Screen Protector - for a ...

In [13]:
import nltk
import re
from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import one_hot
from sklearn.model_selection import train_test_split
from nltk.stem import WordNetLemmatizer

In [14]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
lemmatizer=WordNetLemmatizer()
corpus = []

In [15]:
df1 = df1.drop_duplicates()

In [16]:
len(df1)

434694

In [17]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [18]:
def get_near(s):
  l=str(s).split()
  k=""
  for i in l:
    k=k+i
  return k;

In [19]:
text = df1["text"].apply(lambda x: get_near(x))
text

0         Men'SFullSleeveRaglanT-ShirtsDenimT-ShirtMSize...
1              PrismacolorVerithinColoredPencilsPRISMACOLOR
2                     BlackOpsBMXBrushOffGrips125mmBAeromat
3         USMilitaryT-shirtSoldierThisWe'llDefend-xxxlEr...
4         SonyPCK-LM2AM-LCDScreenProtector-fora(Alpha)SL...
                                ...                        
434689    TrueDesireCameraLensProtector,[HighDefinition]...
434690    MNFashion'sSummerSolidCottonKurtiforWoman(Larg...
434691    TIMBUTemperedGlassforLephoneW15FullScreenCover...
434692        JanasyaWomen'sRedRayonKurtaWithPalazzoJanasya
434693    ThinkTechDesingerPrintedBackCaseCoverCompatibl...
Name: text, Length: 434694, dtype: object

In [20]:
voc_size = 5000
one_hot_rep = [one_hot(words, voc_size) for words in text]

In [21]:
sent_length=20
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2465 1031 1293]
 [   0    0    0 ...    0    0 4317]
 [   0    0    0 ...    0    0 4811]
 ...
 [   0    0    0 ... 1923 4089 1437]
 [   0    0    0 ...    0    0 1694]
 [   0    0    0 ...    0 4744 3649]]


In [22]:
X = embedded_docs
y = df1['BROWSE_NODE_ID']

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [24]:
y

array([1, 0, 0, ..., 2, 8, 5])

In [25]:
len(X)

434694

In [26]:
len(y)

434694

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [29]:
y_pred = gnb.predict(X_test)

In [30]:
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 3.469099023453226
